# Site settings

title: Gapcoin Project
tagline: The Gapcoin project
email: gjh-gapcoin@bel-epa.com
copyright: Gapcoin Project
keywords: prime gap, cryptocurrency, altcoin

description: > # this means to ignore newlines until "url:". One indent required.
  Community resources for Gapcoin, a prime gap based peer-to-peer cryptocurrency

# the base hostname & protocol for your site
url: "https://gapcoin-project.github.io"

twitter_username: gapcoin
github_username:  gapcoin-project

default_image: /img/gapcoin-logo.png

collections:
  gapgraphs:
    output: true
    permalink: /:collection/:path/
  diffgraphs:
    output: true
    permalink: /:collection/:path/
  hashgraphs:
    output: true
    permalink: /:collection/:path/
  paramtests:
    output: true
    permalink: /:collection/:path/
  primegaplist:
    output: true
    permalink: /:collection/:path/
  mining:
    # order:
    #   - introduction.md
    #   - gapminer-tech-basics.md
    #   - chinese-remainder-mining.html
    #   - creating-crt-files.html
    #   - mining-on-a-gpu.md
    #   - mining-pools.md
    #   - shifts-and-primedigits.md
    #   - shift-to-primedigits-mapping.md
    output: true
    permalink: /:collection/:path/


# Pre-processing

markdown: kramdown
highlighter: rouge
safe: true
permalink: pretty # YYYY/MM/DD/page-title/index.html

# lsi: true # Lexical analysis (true) takes longer for higher quality

# sass:
#  style: :compressed

# Build settings
plugins:
  - jekyll-feed

# Default locations
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes

# Lists

tag_items: 20     # Applies to categories and tags lists
recent_items: 10  # Applies to recent posts, apps lists
related_items: 5  # Applies to related posts and apps lists

# Layout

pagebar: true # Show (true) page sidebar menu or hide (false) 
postbar: true # Show (true) post sidebar or hide (false) 

# Features

reading_time: true    # Show est. reading time for posts
facebook: false        # Use facebook features
comments: none      # Switch disqus | facebook | none - comments. facebook = true required for facebook comments

# Embeds

# disqus_name: gapcoin            # Your site name at Disqus

youtube_controls: 1               # Turn on=1/off=0 Youtube player features when embedding videos

# API Keys. PLEASE DO NOT USE THESE KEYS. Get your own at links in comments.

# google_api_key: "" # https://code.google.com/apis/console/
# google_analytics_ua: "" # Google Analytics site specific id
# google_cse_id: "" # Google Custom Search Engine unique id

# facebook_app: "" # https://developers.facebook.com/

# pingdom_rum: "" # https://my.pingdom.com/dashboard. Real User experience (speed) monitoring.

# Exclude from Jekyll processing

include: [".htaccess"]
exclude: ["data", "vendor", "README.md", "node_modules", "gulpfile.js", "package.json", "data", "res", "*.sublime-project", "*.sublime-workspace"]

